### PR TITLE
[Docker] Update README.md

### PR DESCRIPTION
**Pull request by grzegorz-czajkowski**
[Issue] N/A
[Problem] Lack of information how to set up WATT instance on AWS
[Solution] Update README.md

Signed-off-by: Grzegorz Czajkowski <g.czajkowski@samsung.com>

### CODE REVIEW

**Comment by singa2000** [comment]
@lslachciak 
Would you review , please?

**Comment by lslachciak** [comment]
First comment: 
./docker-run.sh assumes that docer-compose is installed Readme says only about docker-ce installaiton
so additional command is needed 
sudo apt-get install docker-compose

**Comment by lslachciak** [comment]
Currently experiencing issue when running ./docker-run.sh
Composing ...
ERROR: Couldn't connect to Docker daemon at http+docker://localunixsocket - is it running?

docker-ce and docker-composer were properly installed

**Comment by grzegorz-czajkowski** [comment]
@lslachciak 
According to first comment.
I added note how to install docker compose. According to docker site the recommend using https://docs.docker.com/compose/install/ not apt-get install.

According to second comment.
This is know issue with docker running without sudo. You need to add your user to docker group.

**Comment by lslachciak** [comment]
>_This is know issue with docker running without sudo. You need to add your user to docker group._
@grzegorz-czajkowski could you add guide for this to README also? I think most of users will use standard Ubuntu configuration

**Comment by lslachciak** [comment]
regarding issue:
_ERROR: Couldn't connect to Docker daemon at http+docker://localunixsocket - is it running?_

this helped:

sudo vigr <-- input your user name in the docker line:

docker:x:999:l.slachciak

than you @grzegorz-czajkowski

**Comment by grzegorz-czajkowski** [comment]
Added note how to run docker without sudo.

**Comment by lslachciak** [comment]
I couldn't finialise verification due to DE npm install error (https://github.com/Samsung/TAU-Design-Editor/issues/20) but current status is OK for me, so approved

**Pull request merged**
