### PR TITLE
Let launch script build TAU

### PR DESCRIPTION
**Pull request by grzegorz-czajkowski**
[Issue] https://github.com/Samsung/WATT/issues/216
[Problem] dist folder has been removed from TAU in [1]
	but WATT requires it for local samples and remote samples for
	code.tizen.org.
[Solution] Build TAU while launching WATT
[Remarks] Requires [2].

[1] https://github.com/Samsung/TAU/commit/62a8d6b4d0f114e61d6ed384949e5565b19a6f1c
[2] https://github.com/Samsung/TAU/pull/630

Signed-off-by: Grzegorz Czajkowski <g.czajkowski@samsung.com>

### CODE REVIEW

**Comment by grzegorz-czajkowski** [comment]
CI fails due to missing commit in TAU: https://github.com/Samsung/TAU/pull/630

**Comment by lslachciak** [comment]
How about upversioning TAU in this PR after merging https://github.com/Samsung/TAU/pull/630?

**Comment by grzegorz-czajkowski** [comment]
> How about upversioning TAU in this PR after merging Samsung/TAU#630?
Added new commit for this.

**Comment by grzegorz-czajkowski** [comment]
I verified this PR in docker env as well.

**Pull request merged**
