### PR TITLE
Skip unsupported test

### PR DESCRIPTION
**Pull request by HunseopJeong**
Wgt build is optional feature. So we don't need to test it when
we don't have proper environment. To skip the test, check the
tizen SDK whether it is installed or not before running the test.

Signed-off-by: Hunseop Jeong <hs85.jeong@samsung.com>

### CODE REVIEW

**Comment by Kwanghyuk-Kim** [comment]
Question,
Is it possible to skip test from configuration stage or before execution ?

**Comment by HunseopJeong** [comment]
I tried to find a way but I didn't find it.
(https://mochajs.org/#inclusive-tests)
mocha support a "skip()" to skip test but it didn't work with asynchronous test.

**Comment by andy-cho** [comment]
You can try to create makefile and make test selectively.

https://github.com/mochajs/mocha/blob/master/Makefile
https://github.com/LearnBoost/websocket.io/blob/master/Makefile

**Comment by Kwanghyuk-Kim** [comment]
may be, can you use skip ?

grep skip from below site.
https://mochajs.org/

**Comment by HunseopJeong** [comment]
As I said, mocha support "skip()" to skip test but it doesn't work with asynchronous test.

**Comment by Kwanghyuk-Kim** [comment]
Ok, you already checked skip. :+1: 

What about inverted grep ?
https://github.com/mochajs/mocha/wiki/Tagging

**Comment by HunseopJeong** [comment]
IMO, inverted grep doesn't look proper either.

**Comment by andy-cho** [comment]
Did you check above makefile-approach?
If you are trying to
   - run default test if some optional features are not present
   - run default + extension test otherwise

Create Makefile with above logic, then call "make test" from npm test script entry
I experimented in my local and seems to work.

**Comment by HunseopJeong** [comment]
#18 seems to be good approach to skip optional feature.
So I close this PR and review new patch in #18.

**Pull request closed without merging**
