### PR TITLE
Add project placeholder image

### PR DESCRIPTION
**Pull request by HunseopJeong**
If the project doesn't have an image, replace it with
a placeholder image

Signed-off-by: Hunseop Jeong <hs85.jeong@samsung.com>

### CODE REVIEW

**Comment by HunseopJeong** [comment]
Don't you like new image?
I think new image expresses that it is empty.

**Comment by hyundukkim** [comment]
I just wonder the reason of selection.
I agree with you if the default icon is provided as 'icon.png' 
and the new image is used in case of no existence of the 'icon.png'.

Still, need to gether opinion from others.

**Comment by Kwanghyuk-Kim** [comment]
What about replacing it with tizen (wind vane) icon ?

**Comment by HunseopJeong** [comment]
What is the tizen (wind vane) icon?
Could you attach image file?

**Comment by Kwanghyuk-Kim** [comment]
https://www.shareicon.net/tizen-102456 may be this one ?

**Comment by HunseopJeong** [comment]
The WATT default image was selected for the placeholder image.
@hyundukkim or @Kwanghyuk-Kim,
Could you merge this PR?

**Pull request merged**
