### PR TITLE
Add LICENSE

### PR DESCRIPTION
**Pull request by HunseopJeong**
Signed-off-by: Hunseop Jeong <hs85.jeong@samsung.com>

### CODE REVIEW

**Comment by HunseopJeong** [comment]
Is there any reason to remain samsuing lincese?
Please refer to other projects on the Samsung page.

**Comment by hyundukkim** [comment]
I have no detailed knowledge on license.

@Kwanghyuk-Kim,
what's your opinion on this ?

**Comment by Kwanghyuk-Kim** [comment]
Invite @somang-park 
Can you review license file on this PR ?

**Comment by somang-park** [comment]
Samsung copyright sentence should be mentioned on top of the license, but It's not MUST action.
There is no issue regarding this patch.

**Pull request merged**
