### PR TITLE
Update TAU Samples

### PR DESCRIPTION
**Pull request by pkaczmarczy**

### CODE REVIEW

**Comment by singa2000** [comment]
@lslachciak 
Would you review the patch and merge it, please?

**Comment by lslachciak** [comment]
I think we can ignore Travis errors related to TAU JS files

**Comment by lslachciak** [comment]
Bak buttn is not working in UIComponents sample app, but I assume this is another issue
similar to https://github.com/Samsung/TAU-Design-Editor/issues/166

**Comment by lslachciak** [comment]
After taking latest DE back button is working

**Pull request merged**
