### PR TITLE
Fix travis build break caused by mongodb installtion on OSX

### PR DESCRIPTION
**Pull request by HunseopJeong**
Used default OSX image and python2 environment

Signed-off-by: Hunseop Jeong <hs85.jeong@samsung.com>

### CODE REVIEW

**Comment by HunseopJeong** [comment]
This PR is that test patch for travis

**Comment by HunseopJeong** [comment]
```
mongodb: A full installation of Xcode.app 8.3.2 is required to compile this software.

Installing just the Command Line Tools is not sufficient.

Xcode can be installed from the App Store.

Error: An unsatisfied requirement failed this build.

Exception is occurred during install mongodb.

Fail to install mongodb. Please install mongodb manually.

(https://docs.mongodb.com/manual/installation/)
```
MongoDB installation seems to be failed on travis.
I will fix on this PR.

**Comment by HunseopJeong** [comment]
@Kwanghyuk-Kim, Could you review this patch?

**Comment by Kwanghyuk-Kim** [comment]
> Fix the travis build on OSX

Insufficient meaning of commit message.
Need to change git comment.
e.g) Fix travis build break caused by mongodb installation on OSX ?

**Comment by HunseopJeong** [comment]
Changed commit message according to your suggestion.

**Pull request merged**
